# Generated by Django 5.2.3 on 2025-07-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_versionpackage_is_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionpackage',
            name='target_library',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
