# Generated by Django 5.2.3 on 2025-07-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_versionpackage_target_library'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['name']},
        ),
    ]
