# Generated by Django 5.2.3 on 2025-07-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_alter_package_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='repository_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
